/*
* Copyright (c) 2018-2019 Confetti Interactive Inc.
*
* This file is part of The-Forge
* (see https://github.com/ConfettiFX/The-Forge).
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/

RWTexture2D<float3> Source : register(u0);
RWTexture2D<float3> Destination : register(u1);

cbuffer RootConstant : register(b0)
{
	uint2 MipSize;
};

[numthreads(16, 16, 1)]
void main(uint3 id : SV_DispatchThreadID)
{    
	if (id.x < MipSize.x && id.y < MipSize.y)
	{
		float3 color = 0.0f;
		[unroll] for (int x = 0; x < 2; ++x)
		{
			[unroll] for (int y = 0; y < 2; ++y)
				color += Source[id.xy * 2 + uint2(x, y)];
		}
		Destination[id.xy] = color * 0.25f;
	}
}
