/*
* Copyright (c) 2018-2019 Confetti Interactive Inc.
*
* This file is part of The-Forge
* (see https://github.com/ConfettiFX/The-Forge).
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/
#version 450 core
#extension GL_EXT_samplerless_texture_functions : enable

layout (local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE, local_size_z = 1 ) in;

layout(set = 3, binding = 0) uniform sampler clampMiplessSampler;
layout(set = 3, binding = 1) uniform texture2D srcImg;
layout(set = 3, binding = 2, r32f) uniform writeonly image2D dstImg;

void main()
{
	ivec2 loc = ivec2(gl_WorkGroupID.xy * WORKGROUP_SIZE + gl_LocalInvocationID.xy);
    float value = texelFetch(srcImg, loc, 0).r;
	imageStore(dstImg, loc, vec4(value, 0.0, 0.0, 1.0));
}