RaytracingAccelerationStructure		gRtScene	: register(t0);
RWTexture2D<float4>					gOutput		: register(u0);

cbuffer gSettings : register(b1)
{
	uint HitGroupIndex;
	uint MissGroupIndex;
}

cbuffer Settings : register(b10)
{
	float3 CameraPosition;
	float3 LightDirection;
}

struct RayPayload
{
	float3 color;
};

[shader("raygeneration")]
void rayGen()
{
	uint2 launchIndex = DispatchRaysIndex().xy;
	uint2 launchDim = DispatchRaysDimensions().xy;

	float2 crd = float2(launchIndex);
	float2 dims = float2(launchDim);

	float2 d = ((crd / dims) * 2.f - 1.f);
	float aspectRatio = dims.x / dims.y;

	RayDesc ray;
	ray.Origin = CameraPosition;
	ray.Direction = normalize(float3(d.x * aspectRatio, -d.y, 1));

	ray.TMin = 0.001;
	ray.TMax = 10000;

	RayPayload payload;
	//TraceRay(gRtScene, 0 /*rayFlags*/, 0xFF, 0 /* ray index*/, 0, 0, ray, payload);
	TraceRay(gRtScene, 0, 0xFF, HitGroupIndex, 0, MissGroupIndex, ray, payload);
	/*
	void TraceRay(RaytracingAccelerationStructure AccelerationStructure,
			  uint RayFlags,
			  uint InstanceInclusionMask,
			  uint RayContributionToHitGroupIndex,
			  uint MultiplierForGeometryContributionToHitGroupIndex,
			  uint MissShaderIndex,
			  RayDesc Ray,
			  inout payload_t Payload);
	*/
	float3 col = payload.color;
	gOutput[launchIndex.xy] = float4(col, 1);
}
