.PHONY: clean All

All:
	@echo "----------Building project:[ VisibilityBuffer - Release ]----------"
	@cd "VisibilityBuffer" && "$(MAKE)" -f  "VisibilityBuffer.mk"
clean:
	@echo "----------Cleaning project:[ VisibilityBuffer - Release ]----------"
	@cd "VisibilityBuffer" && "$(MAKE)" -f  "VisibilityBuffer.mk" clean
