.PHONY: clean All

All:
	@echo "----------Building project:[ OS - Debug ]----------"
	@cd "OSBase" && "$(MAKE)" -f  "OS.mk"
	@echo "----------Building project:[ Renderer - Debug ]----------"
	@cd "Renderer" && "$(MAKE)" -f  "Renderer.mk"
	@echo "----------Building project:[ SpirVTools - Debug ]----------"
	@cd "SpirVTools" && "$(MAKE)" -f  "SpirVTools.mk"
	@echo "----------Building project:[ gainput - Debug ]----------"
	@cd "/home/confetti/Desktop/Gitlab/The-Forge/Common_3/ThirdParty/OpenSource/gainput/Ubuntu/lib" && "$(MAKE)" -f  "gainput.mk"
	@echo "----------Building project:[ EASTL - Debug ]----------"
	@cd "/home/confetti/Desktop/Gitlab/The-Forge/Common_3/ThirdParty/OpenSource/EASTL/Linux" && "$(MAKE)" -f  "EASTL.mk"
	@echo "----------Building project:[ VisibilityBuffer - Debug ]----------"
	@cd "VisibilityBuffer" && "$(MAKE)" -f  "VisibilityBuffer.mk"
clean:
	@echo "----------Cleaning project:[ OS - Debug ]----------"
	@cd "OSBase" && "$(MAKE)" -f  "OS.mk"  clean
	@echo "----------Cleaning project:[ Renderer - Debug ]----------"
	@cd "Renderer" && "$(MAKE)" -f  "Renderer.mk"  clean
	@echo "----------Cleaning project:[ SpirVTools - Debug ]----------"
	@cd "SpirVTools" && "$(MAKE)" -f  "SpirVTools.mk"  clean
	@echo "----------Cleaning project:[ gainput - Debug ]----------"
	@cd "/home/confetti/Desktop/Gitlab/The-Forge/Common_3/ThirdParty/OpenSource/gainput/Ubuntu/lib" && "$(MAKE)" -f  "gainput.mk"  clean
	@echo "----------Cleaning project:[ EASTL - Debug ]----------"
	@cd "/home/confetti/Desktop/Gitlab/The-Forge/Common_3/ThirdParty/OpenSource/EASTL/Linux" && "$(MAKE)" -f  "EASTL.mk"  clean
	@echo "----------Cleaning project:[ VisibilityBuffer - Debug ]----------"
	@cd "VisibilityBuffer" && "$(MAKE)" -f  "VisibilityBuffer.mk" clean
