#version 450 core

layout(set = 3, binding = 0, rgba8) uniform image2D Source;
layout(set = 3, binding = 1, rgba8) uniform image2D Destination;

layout(push_constant) uniform RootConstant_Block
{
	uvec2 MipSize;
} RootConstant;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main()
{    
	uvec3 id = gl_GlobalInvocationID;
	if (id.x < RootConstant.MipSize.x && id.y < RootConstant.MipSize.y)
	{
		vec3 color = vec3(0.0f);
		for (int x = 0; x < 2; ++x)
		{
			for (int y = 0; y < 2; ++y)
				color += imageLoad(Source, ivec2(id.xy) * 2 + ivec2(x, y)).rgb;
		}
		imageStore(Destination, ivec2(id.xy), vec4(color * 0.25f, 1.0f));
	}
}
