/*
 * Copyright (c) 2018-2021 The Forge Interactive Inc.
 *
 * This file is part of The-Forge
 * (see https://github.com/ConfettiFX/The-Forge).
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
*/

#version 450

layout(std430, set = 0, binding = 0) coherent buffer g_tile_counter
{
    uint g_tile_counter_Data[];
};

layout(std430, set = 0, binding = 1) coherent buffer g_ray_counter
{
    uint g_ray_counter_Data[];
};

layout(std430, set = 0, binding = 2) buffer g_intersect_args
{
    uint g_intersect_args_Data[];
};

layout(std430, set = 0, binding = 3) buffer g_denoiser_args
{
    uint g_denoiser_args_Data[];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
    uint tile_counter = g_tile_counter_Data[0];
    uint ray_counter = g_ray_counter_Data[0];

    g_intersect_args_Data[0] = (ray_counter + 63u) / 64u;
    g_intersect_args_Data[1] = 1u;
    g_intersect_args_Data[2] = 1u;

    g_denoiser_args_Data[0] = tile_counter;
    g_denoiser_args_Data[1] = 1u;
    g_denoiser_args_Data[2] = 1u;

    g_tile_counter_Data[0] = 0u;
    g_ray_counter_Data[0] = 0u;
}
