name: "[Linux] Build TF Examples"

on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout The-Forge
      uses: actions/checkout@v3
      with:
        path: The-Forge

    - name: Checkout Custom-Middleware
      uses: actions/checkout@v3
      with:
        path: Custom-Middleware
        repository: ConfettiFX/Custom-Middleware
        # ref: ${{ github.ref_name }}  # Checkout the Custom-Middleware branch with the same name as the The-Forge branch we're building

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install tools and dependencies
      run: |
        # Add Vulkan 1.2.162 source
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.162-bionic.list https://packages.lunarg.com/vulkan/1.2.162/lunarg-vulkan-1.2.162-bionic.list

        sudo apt update
        sudo apt install build-essential codelite make pkg-config libx11-dev libxrandr-dev libgtk-3-dev vulkan-sdk libudev-dev

    - name: Build
      working-directory: The-Forge
      run: python -u ./CI/PyBuild.py --preserveworkingdir --prebuild --printbuildoutput
