/*
 * Copyright (c) 2018 Kostas Anagnostou (https://twitter.com/KostasAAA).
 * 
 * This file is part of The-Forge
 * (see https://github.com/ConfettiFX/The-Forge). 
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file 
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.  
*/

#version 450 core

#extension GL_EXT_samplerless_texture_functions : enable

//#define BACKFACE_CULLING 0
//#include"raytracingCommon.h"

#define USE_SHADOWS_AA 0

layout(set = 0, binding = 0) uniform texture2D shadowsRT;
layout(set = 0, binding = 1, r8) uniform image2D outputRT;

// From "Temporal Reprojection Anti-Aliasing"
// https://github.com/playdeadgames/temporal
vec3 ClipAABB(vec3 aabbMin, vec3 aabbMax, vec3 prevSample, vec3 avg)
{
#if 1
	// note: only clips towards aabb center (but fast!)
	vec3 p_clip = 0.5 * (aabbMax + aabbMin);
	vec3 e_clip = 0.5 * (aabbMax - aabbMin);

	vec3 v_clip = prevSample - p_clip;
	vec3 v_unit = v_clip.xyz / e_clip;
	vec3 a_unit = abs(v_unit);
	float ma_unit = max(a_unit.x, max(a_unit.y, a_unit.z));

	if (ma_unit > 1.0)
		return p_clip + v_clip / ma_unit;
	else
		return prevSample;// point inside aabb
#else
	vec3 r = prevSample - avg;
	vec3 rmax = aabbMax - avg.xyz;
	vec3 rmin = aabbMin - avg.xyz;

	const float eps = 0.000001f;

	if (r.x > rmax.x + eps)
		r *= (rmax.x / r.x);
	if (r.y > rmax.y + eps)
		r *= (rmax.y / r.y);
	if (r.z > rmax.z + eps)
		r *= (rmax.z / r.z);

	if (r.x < rmin.x - eps)
		r *= (rmin.x / r.x);
	if (r.y < rmin.y - eps)
		r *= (rmin.y / r.y);
	if (r.z < rmin.z - eps)
		r *= (rmin.z / r.z);

	return avg + r;
#endif
}

  
#define THREADX 8
#define THREADY 8
#define THREADZ 1
#define THREADGROUPSIZE (THREADX*THREADY*THREADZ)

layout(local_size_x = THREADX, local_size_y = THREADY, local_size_z = THREADZ) in;

void main()
{
	uvec3 DTid = gl_GlobalInvocationID;

	float shadowFactor = texelFetch(shadowsRT, ivec2(DTid.xy), 0).x;

#if USE_SHADOWS_AA  
	float clrMin = 99999999.0f;
	float clrMax = -99999999.0f;

	float m1 = 0.0f;
	float m2 = 0.0f;
	float mWeight = 0.0f;

	for (int y = -1; y <= 1; y++)
	{
		for (int x = -1; x <= 1; x++)
		{
			float2 samplePos = DTid.xy + float2(x, y);

			float tap = shadowsRT[samplePos].x;

			clrMin = min(clrMin, tap);
			clrMax = max(clrMax, tap);

			m1 += tap;
			m2 += tap * tap;
			mWeight += 1.0f;
		}
	}

	//load low res sample
	float history = outputRT[DTid.xy].x;

	history = ClipAABB(clrMin.xxx, clrMax.xxx, history.xxx, m1.xxx / mWeight).x;

	float feedback = 0.9;
	outputRT[DTid.xy] = lerp(shadowFactor, history, feedback);
#else
	imageStore(outputRT, ivec2(DTid.xy), vec4(shadowFactor.x, 0, 0, 0));
#endif

}